/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.Raven.Forms;

import Com.Componentfolders.Service.Impl.KhachHangServiceImpl;
import Com.Componentfolders.Service.KhachHangService;
import Com.Componentfolders.View.KhachHangRetail;
import Com.Componentfolders.ViewModel.KhachHangViewModel;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAVEN
 */
public class Form_1 extends javax.swing.JPanel {

    private KhachHangService khachHangService = new KhachHangServiceImpl();
    private DefaultTableModel defaultTableModel;
    String maa, tenn, sdtt, emaill, cccdd, sexx;

    /**
     * Creates new form Form_1
     */
    public Form_1() {
        initComponents();
        LoadData();

    }

    public void LoadData() {
        ArrayList<KhachHangViewModel> listkh = khachHangService.getListKH();
        defaultTableModel = (DefaultTableModel) tblDSKH.getModel();
        defaultTableModel.setRowCount(0);
        for (KhachHangViewModel kh : listkh) {
            Object[] rowData = {
                kh.getMakh(),
                kh.getTen(),
                kh.getSdt(),
                kh.getGioitinh() == 0 ? "Nam" : "Nữ",
                kh.getCccd(),
                kh.getEmail()

            };
            defaultTableModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTimK = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSKH = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Sách Khách Hàng");

        txtTimK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTimK.setForeground(new java.awt.Color(153, 153, 153));
        txtTimK.setText("  Nhập Mã/Tên/SĐT/CCCD hoặc Email...");
        txtTimK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKFocusGained(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblDSKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblDSKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên", "Số Điện Thoại", "Giới Tính", "CCCD", "Email"
            }
        ));
        tblDSKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSKH);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Thêm Khách Hàng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTimK, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTimK, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed

        // TODO add your handling code here:
        String searchh = txtTimK.getText();
        ArrayList<KhachHangViewModel> listkh = khachHangService.search(searchh);
        defaultTableModel = (DefaultTableModel) tblDSKH.getModel();
        defaultTableModel.setRowCount(0);
        for (KhachHangViewModel kh : listkh) {
            Object[] rowData = {
                kh.getMakh(),
                kh.getTen(),
                kh.getSdt(),
                kh.getGioitinh() == 0 ? "Nam" : "Nữ",
                kh.getCccd(),
                kh.getEmail()

            };
            defaultTableModel.addRow(rowData);
        }
        if (searchh.equals("") || searchh == null) {
            LoadData();
        }

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTimKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKFocusGained
        // TODO add your handling code here:
        if (txtTimK.getText().equals("Nhập Mã/Tên/SĐT/CCCD Hoặc Email")) {
            txtTimK.setText("");
            txtTimK.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTimKFocusGained

    private void tblDSKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSKHMouseClicked
        // TODO add your handling code here:
        int row = tblDSKH.getSelectedRow();
        if (row == -1) {
            return;
        } else {
            maa = tblDSKH.getValueAt(row, 0).toString();
            tenn = tblDSKH.getValueAt(row, 1).toString();
            sdtt = tblDSKH.getValueAt(row, 2).toString();
            sexx = tblDSKH.getValueAt(row, 3).toString();
            cccdd = tblDSKH.getValueAt(row, 4).toString();
            emaill = tblDSKH.getValueAt(row, 5).toString();
        }

    }//GEN-LAST:event_tblDSKHMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        KhachHangRetail k = new KhachHangRetail();
        k.setVisible(true);
        k.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (maa == null) {
            JOptionPane.showMessageDialog(this, "Chọn khách hàng trên danh sách mới có thể sửa! Vui Lòng Chọn");
            return;
        }
        KhachHangRetail k = new KhachHangRetail(maa, tenn, sdtt, cccdd, emaill, sexx);
        k.setVisible(true);
        k.setLocationRelativeTo(null);


    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSKH;
    private javax.swing.JTextField txtTimK;
    // End of variables declaration//GEN-END:variables
}
