/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.componentfolder.Service.Impl.KhachHangServiceImpl;
import com.componentfolder.Service.KhachHangService;
import com.componentfolder.ViewModel.KhachHangViewModel;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAVEN
 */
public class Form_1 extends javax.swing.JPanel {
    private KhachHangService khachHangService = new KhachHangServiceImpl();
    private DefaultTableModel defaultTableModel;
    /**
     * Creates new form Form_1
     */
    public Form_1() {
        initComponents();
        if (btnTimKiem.getText() == "") {
            LoadData();
        }
    }
    public void LoadData(){
        ArrayList<KhachHangViewModel> listkh= khachHangService.getListKH();
        defaultTableModel = (DefaultTableModel) tblDSKH.getModel();
        defaultTableModel.setRowCount(0);
            for (KhachHangViewModel kh : listkh) {                 
                Object[] rowData ={
                    kh.getMakh(),
                    kh.getTen(),
                    kh.getSdt(),
                    kh.getGioitinh() == 0 ?"Nam" : "Nữ",
                    kh.getCccd(),
                    kh.getEmail()
                         
                };
            defaultTableModel.addRow(rowData);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTimK = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSKH = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 106, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Sách Khách Hàng");

        txtTimK.setForeground(new java.awt.Color(153, 153, 153));
        txtTimK.setText("Nhập Mã/Tên/SĐT/CCCD Hoặc Email");

        btnTimKiem.setText("Tìm Kiếm");

        tblDSKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên", "Số Điện Thoại", "Giới Tính", "CCCD", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblDSKH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(txtTimK, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btnTimKiem))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:                                          
        // TODO add your handling code here:
        String searchh = btnTimKiem.getText();       
        ArrayList<KhachHangViewModel> listkh= khachHangService.search(searchh);
        defaultTableModel = (DefaultTableModel) tblDSKH.getModel();
        defaultTableModel.setRowCount(0);
            for (KhachHangViewModel kh : listkh) {                 
                Object[] rowData ={
                    kh.getMakh(),
                    kh.getTen(),
                    kh.getSdt(),
                    kh.getGioitinh() == 0 ?"Nam" : "Nữ",
                    kh.getCccd()
                         
                };
            defaultTableModel.addRow(rowData);
        }
    
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTimKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKFocusGained
        // TODO add your handling code here:
        if(btnTimKiem.getText().equals("Nhập Mã/Tên/SĐT/CCCD Hoặc Email")){
            btnTimKiem.setText("");
            btnTimKiem.setForeground(Color.BLACK);
        }if (btnTimKiem.getText().equals("")) {
            LoadData();
        }
    }//GEN-LAST:event_txtTimKFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSKH;
    private javax.swing.JTextField txtTimK;
    // End of variables declaration//GEN-END:variables
}
