/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;
import Model.ChiTietHopDongModel;
import Model.ChiTietXeModel;
import Model.HopDongModel;

import Service.HopDongService;
import Service.Impl.HopDongServiceImpl;
import View.InHopDong;
import ViewModel.ChiTietHopDongViewModel;
import ViewModel.HopDongViewModel;
import java.awt.Color;
import java.awt.Image;
import java.beans.Customizer;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author RAVEN
 */
public class Form_hopdong extends javax.swing.JPanel {
       private DefaultTableModel defaultTableModel;
    private HopDongService hopDongService = new HopDongServiceImpl();
    private DefaultListModel defaultListModel;
    private DefaultComboBoxModel defaultComboBoxModel;
    String sourceAnh = null;
    /**
     * Creates new form Form_1
     */
    public Form_hopdong() {
        initComponents();
     
    loadHd(hopDongService.getList());
        loadDataChiTiet(hopDongService.getListChiTiet());
        addCbid(hopDongService.getCbid());
        addCbHd(hopDongService.getCbHd()); 
        addGr();
    }
    ButtonGroup btn = new ButtonGroup();
    void addGr(){
        btn.add(rdo_chuaky);
        btn.add(rdo_daky);
    }
    void loadHd(ArrayList<HopDongViewModel> list){
       defaultTableModel = (DefaultTableModel) tbl_hopdong.getModel();
       defaultTableModel.setRowCount(0);
       for(HopDongViewModel x:list){
           defaultTableModel.addRow(new Object[]{
               x.getMahd(),hopDongService.tenNhanVien(x.getIdnv()),hopDongService.tenKhachHang(x.getIdkh()),x.getNgayTao(),
               x.getNgayHetHan(),x.hienThiTinhTrang(),x.getSourceAnh(),
           });
           
           
       }
       
   }
 
    void loadDataChiTiet(ArrayList<ChiTietHopDongViewModel> list){
        defaultTableModel = (DefaultTableModel) tbl_chitiet.getModel();
        defaultTableModel.setRowCount(0);
        for(ChiTietHopDongViewModel x:list){
            defaultTableModel.addRow(new Object[]{
                x.getMahd(),x.getBienso(),x.getTiencoc()
            });
        }
    }    
    void addCbid(ArrayList<String> list){
        defaultComboBoxModel = (DefaultComboBoxModel) cbo_bienso.getModel();
        for(String chiTietXeModel:list){
            defaultComboBoxModel.addElement(chiTietXeModel);
        }
    }
    void addCbHd(ArrayList<String> list){
        defaultComboBoxModel = (DefaultComboBoxModel) cbo_idhopdong.getModel();
        for(String x:list){
            defaultComboBoxModel.addElement(x);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_xoahopdong = new javax.swing.JButton();
        txt_tenkhachhang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rdo_chuaky = new javax.swing.JRadioButton();
        rdo_daky = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        btn_addhopdong = new javax.swing.JButton();
        btn_updatehd = new javax.swing.JButton();
        txt_ngaytao = new com.toedter.calendar.JDateChooser();
        txt_ngayhethan = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txt_tennv = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_mahd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_thongtinthem = new javax.swing.JLabel();
        txt_search1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clearchitiet = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_tiencoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbo_bienso = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbo_idhopdong = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_chitiet = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_searchchitiet = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_hopdong = new javax.swing.JTable();

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Print.png"))); // NOI18N
        jButton2.setText("In hợp đồng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(47, 157, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Quản lý hợp đồng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ngày hết hạn");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tên khách hàng");

        btn_xoahopdong.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_xoahopdong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        btn_xoahopdong.setText("Xóa");
        btn_xoahopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoahopdongActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tình trạng");

        rdo_chuaky.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdo_chuaky.setText("chưa ký");

        rdo_daky.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdo_daky.setText("đã ký");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ngày tạo");

        btn_addhopdong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        btn_addhopdong.setText("Thêm");
        btn_addhopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addhopdongActionPerformed(evt);
            }
        });

        btn_updatehd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Gear.png"))); // NOI18N
        btn_updatehd.setText("Sửa");
        btn_updatehd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatehdActionPerformed(evt);
            }
        });

        txt_ngaytao.setDateFormatString("yyyy-MM-dd");

        txt_ngayhethan.setDateFormatString("yyyy-MM-dd");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mã hợp đồng");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tên nhân viên");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Thông tin thêm");

        txt_thongtinthem.setText("Nhấn vào đây để thêm ảnh");
        txt_thongtinthem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_thongtinthemMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_thongtinthemMousePressed(evt);
            }
        });

        txt_search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_search1MouseClicked(evt);
            }
        });
        txt_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search1ActionPerformed(evt);
            }
        });
        txt_search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search1KeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        jLabel13.setText("Tìm kiếm thông tin hợp đồng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rdo_chuaky)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rdo_daky))
                                .addComponent(txt_tenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_mahd, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_addhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_updatehd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_xoahopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txt_thongtinthem, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(txt_ngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngayhethan, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16)
                                            .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addComponent(txt_thongtinthem, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txt_tenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rdo_daky)
                                                    .addComponent(rdo_chuaky))))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(txt_mahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn_addhopdong)
                                            .addComponent(btn_updatehd)
                                            .addComponent(btn_xoahopdong)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_ngayhethan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txt_ngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(12, 93, 118));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Quản lý chi tiết hợp đồng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Gear.png"))); // NOI18N
        btn_update.setText("Sửa");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clearchitiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Left.png"))); // NOI18N
        btn_clearchitiet.setText("Clear");
        btn_clearchitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearchitietActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tiền cọc");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Biển số");

        cbo_bienso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn biển số xe" }));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Hợp Đồng");

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Print.png"))); // NOI18N
        jButton3.setText("In hợp đồng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_clearchitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_idhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_bienso, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tiencoc, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbo_idhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbo_bienso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tiencoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_update)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clearchitiet)
                    .addComponent(btn_delete)))
        );

        jPanel8.setBackground(new java.awt.Color(12, 93, 118));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Chi tiết hợp đồng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbl_chitiet.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_chitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Hợp đồng", "Biển số", "Tiền cọc"
            }
        ));
        tbl_chitiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_chitietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_chitiet);

        jScrollPane5.setViewportView(jScrollPane2);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        jLabel7.setText("Tìm kiếm thông tin chi tiết hợp đồng");

        txt_searchchitiet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchchitietKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_searchchitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_searchchitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(47, 157, 191));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Hợp Đồng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        tbl_hopdong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tbl_hopdong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hợp đồng", "Tên nhân viên", "Tên khách hàng", "ngày tạo", "ngày hết hạn", "Tình trạng", "Thông tin thêm"
            }
        ));
        tbl_hopdong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hopdongMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_hopdong);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(445, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(516, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xoahopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoahopdongActionPerformed
        // TODO add your handling code here:
        ArrayList<HopDongModel> list = new ArrayList<>();
        int row = tbl_hopdong.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "hãy chọn một dòng rồi ấn nút xóa");

        }else{
            int luachon= JOptionPane.showConfirmDialog(this, "bạn chắc muốn xóa chứ ?","Xóa",JOptionPane.YES_NO_OPTION);
            if(luachon ==0){
                String id = txt_mahd.getText().toString();
                if(hopDongService.delete(id)){
                    JOptionPane.showMessageDialog(this, "thanh cong");
                    loadHd(hopDongService.getList());
                }else
                JOptionPane.showMessageDialog(this, "that bai");
            }
        }
    }//GEN-LAST:event_btn_xoahopdongActionPerformed

    private void tbl_hopdongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hopdongMouseClicked
        DefaultTableModel dtm = new DefaultTableModel();
        int row = tbl_hopdong.getSelectedRow();
        txt_mahd.setText(tbl_hopdong.getValueAt(row, 0).toString());
        txt_tennv.setText(tbl_hopdong.getValueAt(row, 1).toString());
        txt_tenkhachhang.setText(tbl_hopdong.getValueAt(row, 2).toString());
        try {
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) tbl_hopdong.getValueAt(row, 3).toString());
            java.util.Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse((String) tbl_hopdong.getValueAt(row, 4).toString());
            txt_ngaytao.setDate(date);
            txt_ngayhethan.setDate(date2);
        } catch (ParseException ex) {
           
        }

        if(tbl_hopdong.getValueAt(row, 5).toString().equalsIgnoreCase("chưa ký")){
            rdo_chuaky.setSelected(true);
        }else
        rdo_daky.setSelected(true);

        txt_thongtinthem.setText("");
        sourceAnh = (String) tbl_hopdong.getValueAt(row, 6);
        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/Anh/" +  sourceAnh));
        Image img = imgIcon.getImage();
        img.getScaledInstance(txt_thongtinthem.getWidth(), txt_thongtinthem.getY(), 0);
        txt_thongtinthem.setIcon(imgIcon);

    }//GEN-LAST:event_tbl_hopdongMouseClicked

    private void btn_addhopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addhopdongActionPerformed
        // TODO add your handling code here:
        String p_hoten = "[a-zA-Z ]+";
        String p_mahd = "[A-Za-z0-9]+";
        if(txt_tenkhachhang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "chưa điền tên khách hàng");
            txt_tenkhachhang.requestFocus();
            txt_tenkhachhang.setBackground(Color.red);
            txt_tenkhachhang.setText("");
            return;
        }
        if(txt_tennv.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "chưa điền tên nhân viên");
            txt_tennv.requestFocus();
            txt_tennv.setBackground(Color.red);
            txt_tennv.setText("");
            return;
        }
        if(txt_mahd.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "chưa điền mã hợp đồng");
            txt_mahd.requestFocus();
            txt_mahd.setBackground(Color.red);
            txt_mahd.setText("");
            return;
        }

        HopDongModel hopDongModel = new HopDongModel();
        hopDongModel.setMahd(txt_mahd.getText().toString());
        hopDongModel.setIdnv(hopDongService.idnhanvien(txt_tennv.getText().toString()));
        hopDongModel.setIdkh(hopDongService.idkhachhang(txt_tenkhachhang.getText().toString()));

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date1 = sdf.format(txt_ngaytao.getDate());
            String date2 = sdf.format(txt_ngayhethan.getDate());
            hopDongModel.setNgayTao(sdf.parse(date1));
            hopDongModel.setNgayHetHan(sdf.parse(date2));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "chưa chọn ngày");
        }

        hopDongModel.setSourceAnh(sourceAnh);

        int tinhTrang = 0;
        if(rdo_daky.isSelected()){
            tinhTrang = 1;
        }
        hopDongModel.setTinhTrang(tinhTrang);
        if(hopDongService.add(hopDongModel)){
            JOptionPane.showMessageDialog(this, "thành công");
            loadHd(hopDongService.getList());
        }else
        JOptionPane.showMessageDialog(this, "thất bại");
    }//GEN-LAST:event_btn_addhopdongActionPerformed

    private void btn_updatehdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatehdActionPerformed
        // TODO add your handling code here:
        int row = tbl_hopdong.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "hãy chọn một dòng rồi ấn nút update");

        }else{
            HopDongModel hopDongModel = new HopDongModel();
            String id = txt_mahd.getText().toString();
            hopDongModel.setIdnv(hopDongService.idnhanvien(txt_tennv.getText().toString()));
            hopDongModel.setIdkh(hopDongService.idkhachhang(txt_tenkhachhang.getText().toString()));
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date1 = sdf.format(txt_ngaytao.getDate());
                String date2 = sdf.format(txt_ngayhethan.getDate());
                hopDongModel.setNgayTao(sdf.parse(date1));
                hopDongModel.setNgayHetHan(sdf.parse(date2));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "chưa chọn ngày");
            }
            int tinhTrang = 0;
            if(rdo_daky.isSelected()){
                tinhTrang = 1;

            }
            hopDongModel.setMahd(txt_mahd.getText().toString());
            hopDongModel.setSourceAnh(sourceAnh);
            hopDongModel.setTinhTrang(tinhTrang);
            if(hopDongService.update2(hopDongModel, id)){
                JOptionPane.showMessageDialog(this, "update thành công");
                loadHd(hopDongService.getList());
            }else
            JOptionPane.showMessageDialog(this, "thất bại");
    }//GEN-LAST:event_btn_updatehdActionPerformed

    private void txt_thongtinthemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_thongtinthemMouseClicked
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            JFileChooser jfc = new JFileChooser("C:\\Users\\Admin\\Downloads\\DuAn1\\src\\icon");
            jfc.showOpenDialog(null);
            File file = jfc.getSelectedFile();
            Image img = ImageIO.read(file);
            sourceAnh = file.getName();
            txt_thongtinthem.setText("");
            int width = txt_thongtinthem.getWidth();
            int height = txt_thongtinthem.getHeight();

            txt_thongtinthem.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
        } catch (IOException ex) {
          
        }
    }//GEN-LAST:event_txt_thongtinthemMouseClicked

    private void txt_thongtinthemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_thongtinthemMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_thongtinthemMousePressed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        String p_scmt = "[0-9]{1,12}";

        if(txt_tiencoc.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "chưa điền tiền cọc");
            txt_tiencoc.requestFocus();
            txt_tiencoc.setBackground(Color.red);
            txt_tiencoc.setText("");
            return;
        }else
        if(txt_tiencoc.getText().matches(p_scmt)==false){
            JOptionPane.showMessageDialog(this, "tiền cọc sai định dạng");
            txt_tiencoc.requestFocus();
            txt_tiencoc.setBackground(Color.red);
            txt_tiencoc.setText("");
            return;
        }
        ChiTietHopDongModel chiTietHopDongModel = new ChiTietHopDongModel();
        chiTietHopDongModel.setMahd(cbo_idhopdong.getSelectedItem().toString());
        chiTietHopDongModel.setBienso(cbo_bienso.getSelectedItem().toString());
        chiTietHopDongModel.setTienCoc(Float.parseFloat(txt_tiencoc.getText().toString()));
        if(hopDongService.addChiTiet(chiTietHopDongModel)){
            JOptionPane.showMessageDialog(this, "thành công");
            loadDataChiTiet(hopDongService.getListChiTiet());
        }else
        JOptionPane.showMessageDialog(this, "that bai");
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int row = tbl_chitiet.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "hãy chọn một dòng rồi ấn nút update");

        }else{
            ChiTietHopDongModel chiTietHopDongModel = new ChiTietHopDongModel();
            chiTietHopDongModel.setMahd(cbo_idhopdong.getSelectedItem().toString());
            chiTietHopDongModel.setBienso(cbo_bienso.getSelectedItem().toString());

            chiTietHopDongModel.setTienCoc(Float.parseFloat(txt_tiencoc.getText().toString()));
            String idhd = cbo_idhopdong.getSelectedItem().toString();
            if(hopDongService.updateChiTiet(chiTietHopDongModel, idhd)){
                JOptionPane.showMessageDialog(this, "thành công");
                loadDataChiTiet(hopDongService.getListChiTiet());
            }else
            JOptionPane.showMessageDialog(this, "that bai");
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        ArrayList<ChiTietHopDongModel> list = new ArrayList<>();
        int row = tbl_chitiet.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "hãy chọn một dòng rồi ấn nút xóa");

        }else{
            int luachon= JOptionPane.showConfirmDialog(null, "bạn chắc muốn xóa chứ ?","Xóa",JOptionPane.YES_NO_OPTION);
            if(luachon ==0){
                String idhd = cbo_idhopdong.getSelectedItem().toString();
                if(hopDongService.DeleteChiTiet(idhd)){
                    JOptionPane.showMessageDialog(this, "thanh cong");
                    loadDataChiTiet(hopDongService.getListChiTiet());
                }else
                JOptionPane.showMessageDialog(this, "that bai");
            }
        }

    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearchitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearchitietActionPerformed
        // TODO add your handling code here:
        txt_tiencoc.setText("");
    }//GEN-LAST:event_btn_clearchitietActionPerformed

    private void txt_searchchitietKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchchitietKeyPressed
        // TODO add your handling code here:
        defaultTableModel = (DefaultTableModel) tbl_chitiet.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(defaultTableModel);
        tbl_chitiet.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txt_searchchitiet.getText().trim()));
    }//GEN-LAST:event_txt_searchchitietKeyPressed

    private void tbl_chitietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_chitietMouseClicked
        // TODO add your handling code here:
        int row = tbl_chitiet.getSelectedRow();
        cbo_idhopdong.setSelectedItem(tbl_chitiet.getValueAt(row, 0).toString());
        cbo_bienso.setSelectedItem(tbl_chitiet.getValueAt(row, 1).toString());
        txt_tiencoc.setText(tbl_chitiet.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tbl_chitietMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new InHopDong().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_search1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_search1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1MouseClicked

    private void txt_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1ActionPerformed

    private void txt_search1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search1KeyPressed
        // TODO add your handling code here:
        defaultTableModel = (DefaultTableModel) tbl_hopdong.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(defaultTableModel);
        tbl_hopdong.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txt_search1.getText().trim()));
    }//GEN-LAST:event_txt_search1KeyPressed

    private void txt_search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_addhopdong;
    private javax.swing.JButton btn_clearchitiet;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_updatehd;
    private javax.swing.JButton btn_xoahopdong;
    private javax.swing.JComboBox<String> cbo_bienso;
    private javax.swing.JComboBox<String> cbo_idhopdong;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton rdo_chuaky;
    private javax.swing.JRadioButton rdo_daky;
    private javax.swing.JTable tbl_chitiet;
    private javax.swing.JTable tbl_hopdong;
    private javax.swing.JTextField txt_mahd;
    private com.toedter.calendar.JDateChooser txt_ngayhethan;
    private com.toedter.calendar.JDateChooser txt_ngaytao;
    private javax.swing.JTextField txt_search1;
    private javax.swing.JTextField txt_searchchitiet;
    private javax.swing.JTextField txt_tenkhachhang;
    private javax.swing.JTextField txt_tennv;
    private javax.swing.JLabel txt_thongtinthem;
    private javax.swing.JTextField txt_tiencoc;
    // End of variables declaration//GEN-END:variables
}
