/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.componentfolder.Model.DangNhap;
import com.componentfolder.Model.NhanVienModel;
import com.componentfolder.Repository.NhanVienTKRePo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAVEN
 */
public class Form_NhanVien extends javax.swing.JPanel {
    private DefaultTableModel defaultTableModel;
    private NhanVienTKRePo nhanvienService = new NhanVienTKRePo();
    private int coutnv = nhanvienService.getcountDB();
    /**
     * Creates new form Form_1
     */
    public Form_NhanVien() {
        initComponents();
        LoadData();
    }
    public void LoadData(){
        ArrayList<NhanVienModel> listkh= nhanvienService.getListKh();
        defaultTableModel = (DefaultTableModel) jTable1.getModel();
        defaultTableModel.setRowCount(0);
            for (NhanVienModel kh : listkh) {                 
                Object[] rowData ={
                    kh.getId(),
                    kh.getTen(),
                    kh.getSdt(),
                    kh.getGioiTinh()== 0 ?"Nam" : "Nữ",
                    kh.taikhoan().getTaikhoan()
                         
                };
            defaultTableModel.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbbChucVU = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttenNhanVien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 106, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Nhân Viên");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Tài Khoản:");

        jLabel3.setText("Chức Vụ:");

        cbbChucVU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Quản Lý" }));

        jLabel4.setText("Mật Khẩu:");

        jLabel5.setText("Mã NV:");

        txtMaNV.setEditable(false);
        txtMaNV.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Tên NV:");

        jLabel7.setText("Giới Tính:");

        rdoNam.setText("Nam");

        rdoNu.setText("Nữ");

        jLabel8.setText("SĐT:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên", "SĐT", "Giới Tính", "Tài Khoản"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTK)
                    .addComponent(txtMatKhau)
                    .addComponent(txttenNhanVien)
                    .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(9, 9, 9)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoNam)
                        .addGap(18, 18, 18)
                        .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbbChucVU, 0, 134, Short.MAX_VALUE)
                        .addComponent(txtMaNV))
                    .addComponent(btnSua))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbbChucVU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnSua))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        NhanVienModel kh = new NhanVienModel();      
        DangNhap dn = new DangNhap(); 
        for (int i = 0; i <= coutnv; i++) {
            kh.setId("NV" + (i + 1));
        }
        coutnv++;
        if(txttenNhanVien.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui Lòng Không Để trống Tên Nhân Viên");
            return;
        }if(txtSDT.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui Lòng Không Để trống SĐT");
            return;
        }if(txtTK.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui Lòng Không Để trống tài Khoản");
            return;
        }if(txtMatKhau.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui Lòng Không Để trống tài Khoản");
            return;
        }
        kh.setTen(txttenNhanVien.getText());
        if(rdoNam.isSelected()){
        kh.setGioiTinh(0);
        }else{kh.setGioiTinh(1);}
        kh.setSdt(txtSDT.getText());
        if (rdoNam.isSelected()) {
            kh.setGioiTinh(0);
        }else{ kh.setGioiTinh(1);
        }
        dn.setTaikhoan(txtTK.getText());
        dn.setMatkhau(txtMatKhau.getText());
        dn.setChucvu(cbbChucVU.getSelectedItem().toString());
        if(nhanvienService.add(kh,dn)){
        JOptionPane.showMessageDialog(null, "Thêm mới Nhân Viên thành công");
        }else{
        JOptionPane.showMessageDialog(null, "Thêm mới Nhân Viên không thành công");}
        LoadData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        NhanVienModel kh = new NhanVienModel();      
        DangNhap dn = new DangNhap(); 
        for (int i = 0; i <= coutnv; i++) {
            kh.setId("NV" + (i + 1));
        }
        coutnv++;
        if(txttenNhanVien.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui Lòng Không Để trống Tên Nhân Viên");
            return;
        }if(txtSDT.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui Lòng Không Để trống SĐT");
            return;
        }if(txtTK.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui Lòng Không Để trống tài Khoản");
            return;
        }if(txtMatKhau.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui Lòng Không Để trống tài Khoản");
            return;
        }if(txtMaNV.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Mã Nhân Viên Đang Trống! Vui Lòng Chọn 1 Nhân Viên Trên Danh Sách Để Sửa!");
        }
        kh.setId(txtMaNV.getText());
        kh.setTen(txttenNhanVien.getText());
        if(rdoNam.isSelected()){
        kh.setGioiTinh(0);
        }else{kh.setGioiTinh(1);}
        kh.setSdt(txtSDT.getText());
        if (rdoNam.isSelected()) {
            kh.setGioiTinh(0);
        }else{ kh.setGioiTinh(1);
        }
        dn.setTaikhoan(txtTK.getText());
        dn.setMatkhau(txtMatKhau.getText());
        dn.setChucvu(cbbChucVU.getSelectedItem().toString());
        if(nhanvienService.update(kh,dn)){
        JOptionPane.showMessageDialog(null, "Thêm mới Nhân Viên thành công");
        }else{
        JOptionPane.showMessageDialog(null, "Thêm mới Nhân Viên không thành công");}
        LoadData();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if(row == -1){
            return;
        }
        txtTK.setText(jTable1.getValueAt(row, 4).toString());
        txttenNhanVien.setText(jTable1.getValueAt(row, 1).toString());
        txtMaNV.setText(jTable1.getValueAt(row, 0).toString());
        txtSDT.setText(jTable1.getValueAt(row, 2).toString());
        if(jTable1.getValueAt(row, 2).toString().equals("Nam")){
            rdoNam.setSelected(true); 
        }else{rdoNu.setSelected(true); }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbChucVU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txttenNhanVien;
    // End of variables declaration//GEN-END:variables
}
