/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.componentfolder.View;

import com.componentfolder.Service.HopDongService;
import com.componentfolder.Service.Impl.HopDongServiceImpl;
import ViewModel.InHopDongViewModel;
import com.raven.main.Main;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author User
 */
public class InHopDong extends javax.swing.JFrame {
   
    private HopDongService hopDongService = new HopDongServiceImpl();
    private DefaultTableModel defaultTableModel;

    /**
     * Creates new form InHopDong
     */
    public InHopDong() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadData(hopDongService.getListIn());
    }
    void loadData(ArrayList<InHopDongViewModel> list){
        defaultTableModel = (DefaultTableModel) tbl_in.getModel();
        defaultTableModel.setRowCount(0);
        for(InHopDongViewModel x:list){
            defaultTableModel.addRow(new Object[]{
                x.getTen(),x.getCccd(),x.getBienso(),x.getTiencoc(),x.getNgaytao(),x.getNgayhethan()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Panel_hd2 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        txt_tenkh4 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        txt_cccd2 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        txt_bienso2 = new javax.swing.JLabel();
        txt_giathue2 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        txt_ngayhethan2 = new javax.swing.JLabel();
        txt_ngaytao2 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        txt_tenkh5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_in = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel5.setBackground(new java.awt.Color(0, 153, 102));

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Mẫu Hợp Đồng");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Panel_hd2.setBackground(new java.awt.Color(255, 255, 255));
        Panel_hd2.setForeground(new java.awt.Color(255, 255, 255));
        Panel_hd2.setPreferredSize(new java.awt.Dimension(1220, 860));

        jLabel60.setBackground(new java.awt.Color(0, 0, 0));
        jLabel60.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel60.setText("CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM");

        jLabel61.setBackground(new java.awt.Color(0, 0, 0));
        jLabel61.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel61.setText("Độc lập - Tự do - Hạnh phúc --------oOo-----------");

        jLabel62.setBackground(new java.awt.Color(0, 0, 0));
        jLabel62.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel62.setText("HỢP ĐỒNG THUÊ XE");

        jLabel63.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel63.setText("- Căn cứ Bộ Luật Dân sự số 91/2015/QH13 đã được Quốc Hội nước Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam thông qua ngày  ");

        jLabel64.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel64.setText("XI,kỳ họp thứ 7 thông qua ngày 14/6/2005");

        jLabel65.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel65.setText("- Căn cứ luật thương mại số 36/2005/QH11 đã được Quốc Hội nước Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam thông qua khóa");

        jLabel66.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel66.setText("- Căn cứ vào nhu cầu và khả năng cung ứng của các bên dưới đây.");

        jLabel67.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel67.setText("- Số căn cước công dân/ chứng minh thư:");

        jLabel68.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel68.setText("Bên A :");

        txt_tenkh4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel69.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel69.setText("(Bên Thuê)");

        jLabel70.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel70.setText("Sau khi bàn bạc , thỏa thuận,hai bên thống nhất ký kết hợp đồng thuê xe với các điều khoản như sau ");

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel71.setText("Bên B :");

        jLabel72.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel72.setText("- Địa chỉ:");

        jLabel73.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel73.setText("- Đại diện:");

        jLabel74.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel74.setText("CÔNG TY CHO THUÊ XE HÀ NỘI");

        jLabel75.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel75.setText("(Bên Cho Thuê)");

        jLabel76.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel76.setText("Nguyễn Ngọc Minh");

        jLabel77.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel77.setText("65 Nam Từ Liêm , Hà Nội");

        jLabel78.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel78.setText("- Chức vụ :");

        jLabel79.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel79.setText("Giám đốc");

        txt_cccd2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txt_cccd2.setText("...............");

        jLabel80.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel80.setText("1 . Bên A đồng ý thuê bên B một xe:");

        jLabel81.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel81.setText("Biển kiểm soát :");

        txt_bienso2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txt_bienso2.setText("................");

        txt_giathue2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txt_giathue2.setText("...............");

        jLabel82.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel82.setText("3. Hợp đồng có giá trị kể từ ngày");

        jLabel83.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel83.setText("đến hết ngày:");

        jLabel84.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel84.setText("2. Tiền cọc thuê xe là :");

        txt_ngayhethan2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txt_ngayhethan2.setText(".........................");

        txt_ngaytao2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txt_ngaytao2.setText(".........................");

        jLabel85.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel85.setText("Đại diện bên B");

        jLabel86.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel86.setText("Đại diện bên A");

        jLabel87.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel87.setText("24/11/2015");

        txt_tenkh5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txt_tenkh5.setText("Ông/Bà:");

        javax.swing.GroupLayout Panel_hd2Layout = new javax.swing.GroupLayout(Panel_hd2);
        Panel_hd2.setLayout(Panel_hd2Layout);
        Panel_hd2Layout.setHorizontalGroup(
            Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_hd2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_hd2Layout.createSequentialGroup()
                        .addComponent(jLabel86)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel85))
                    .addGroup(Panel_hd2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_hd2Layout.createSequentialGroup()
                                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_hd2Layout.createSequentialGroup()
                                        .addComponent(jLabel84)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_giathue2))
                                    .addGroup(Panel_hd2Layout.createSequentialGroup()
                                        .addComponent(jLabel80)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel81)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_bienso2))
                            .addGroup(Panel_hd2Layout.createSequentialGroup()
                                .addComponent(jLabel82)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ngaytao2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel83)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ngayhethan2)))
                        .addGap(0, 273, Short.MAX_VALUE)))
                .addGap(167, 167, 167))
            .addGroup(Panel_hd2Layout.createSequentialGroup()
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_hd2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_hd2Layout.createSequentialGroup()
                                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel68, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel71))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_hd2Layout.createSequentialGroup()
                                        .addComponent(txt_tenkh5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(183, 183, 183)
                                        .addComponent(jLabel69))
                                    .addGroup(Panel_hd2Layout.createSequentialGroup()
                                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel75))))
                            .addComponent(jLabel70)
                            .addGroup(Panel_hd2Layout.createSequentialGroup()
                                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel67)
                                    .addComponent(txt_tenkh4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cccd2))))
                    .addGroup(Panel_hd2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel87)
                            .addComponent(jLabel64)))
                    .addGroup(Panel_hd2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_hd2Layout.createSequentialGroup()
                                .addComponent(jLabel73)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel78)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_hd2Layout.createSequentialGroup()
                                .addComponent(jLabel72)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_hd2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_hd2Layout.createSequentialGroup()
                        .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel65)
                            .addComponent(jLabel63)
                            .addComponent(jLabel66))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_hd2Layout.createSequentialGroup()
                        .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_hd2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_hd2Layout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addGap(486, 486, 486))))
        );
        Panel_hd2Layout.setVerticalGroup(
            Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_hd2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel61)
                .addGap(28, 28, 28)
                .addComponent(jLabel62)
                .addGap(43, 43, 43)
                .addComponent(jLabel63)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel87)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel66)
                .addGap(42, 42, 42)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(txt_tenkh4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69)
                    .addComponent(txt_tenkh5))
                .addGap(30, 30, 30)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(txt_cccd2))
                .addGap(25, 25, 25)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(jLabel74)
                    .addComponent(jLabel75))
                .addGap(18, 18, 18)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jLabel77))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(jLabel76)
                    .addComponent(jLabel78)
                    .addComponent(jLabel79))
                .addGap(18, 18, 18)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(jLabel81)
                    .addComponent(txt_bienso2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel84)
                    .addComponent(txt_giathue2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(txt_ngaytao2)
                    .addComponent(jLabel83)
                    .addComponent(txt_ngayhethan2))
                .addGap(48, 48, 48)
                .addGroup(Panel_hd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(jLabel85))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(Panel_hd2);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbl_in.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên khách hàng", "Căn cước/chứng minh thư", "Biển kiểm soát", "Tiền cọc", "Ngày tạo", "Ngày hết hạn"
            }
        ));
        tbl_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_inMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_in);

        jScrollPane2.setViewportView(jScrollPane3);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/componentfolder/Image/Home.png"))); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/componentfolder/Image/Print preview.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_inMouseClicked
        // TODO add your handling code here:
        int row = tbl_in.getSelectedRow();
        txt_tenkh4.setText(tbl_in.getValueAt(row, 0).toString());
        txt_cccd2.setText(tbl_in.getValueAt(row, 1).toString());
        txt_bienso2.setText(tbl_in.getValueAt(row, 2).toString());
        txt_giathue2.setText(tbl_in.getValueAt(row, 3).toString());
        txt_ngaytao2.setText(tbl_in.getValueAt(row, 4).toString());
        txt_ngayhethan2.setText(tbl_in.getValueAt(row, 5).toString());
        
        
    }//GEN-LAST:event_tbl_inMouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        int row = tbl_in.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "hãy chọn 1 dòng rồi ấn In");
        }else{
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");

            job.setPrintable(new Printable(){
                public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                    if(pageNum > 0){
                        return Printable.NO_SUCH_PAGE;
                    }

                    Graphics2D g2 = (Graphics2D)pg;
                    g2.translate(pf.getImageableX(), pf.getImageableY());
                    g2.scale(0.47,0.47);

                    Panel_hd2.print(g2);

                    return Printable.PAGE_EXISTS;

                }
            });
            boolean ok = job.printDialog();
            if(ok){
                try{

                    job.print();
                }
                catch (PrinterException ex){
                    ex.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InHopDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InHopDong().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_hd2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbl_in;
    private javax.swing.JLabel txt_bienso2;
    private javax.swing.JLabel txt_cccd2;
    private javax.swing.JLabel txt_giathue2;
    private javax.swing.JLabel txt_ngayhethan2;
    private javax.swing.JLabel txt_ngaytao2;
    private javax.swing.JLabel txt_tenkh4;
    private javax.swing.JLabel txt_tenkh5;
    // End of variables declaration//GEN-END:variables
}
